/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2026-05-04 03:50:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>REIVAN - Premium Computer Store</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link href=\"CSS/estilos.css?v=3\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header-principal\">\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("            <a href=\"index.jsp\"><img src=\"imagenes/logo_r_transparent.png\" alt=\"Logo Reivan\" class=\"logo-imagen\" style=\"border: none;\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"textos-header\">\r\n");
      out.write("            <h1>REIVAN</h1>\r\n");
      out.write("            <h2 class=\"destacado\">Premium Computer Store</h2>\r\n");
      out.write("            <h4 id=\"favorito\">Mejora tu Pc Hoy mismo</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a class=\"active\" href=\"index.jsp\">Inicio</a>\r\n");
      out.write("        <a href=\"construccion.jsp\">Servicios</a>\r\n");
      out.write("        <a href=\"construccion.jsp\">Contacto</a>\r\n");
      out.write("        <a href=\"login.jsp\">Iniciar Sesión</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <section>\r\n");
      out.write("                <article>\r\n");
      out.write("                    <h3>Nuestra misión</h3>\r\n");
      out.write("                    <p>Esta empresa tiene 12 años de experiencia. Buscamos integrar más el hardware a tu vida,\r\n");
      out.write("                        mejorando tu experiencia.</p>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"carouselExampleSlidesOnly\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                        <div class=\"carousel-inner rounded shadow-sm\">\r\n");
      out.write("                            <div class=\"carousel-item active\">\r\n");
      out.write("                                <img class=\"d-block w-100\" src=\"imagenes/slider1.png\" alt=\"Slider 1\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img class=\"d-block w-100\" src=\"imagenes/slider2.png\" alt=\"Slider 2\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img class=\"d-block w-100\" src=\"imagenes/slider3.png\" alt=\"Slider 3\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mapa-container mt-4\">\r\n");
      out.write("                        <h4 class=\"mb-3\">Nuestra Ubicación</h4>\r\n");
      out.write("                        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15610.749005953046!2d-79.04351337674712!3d-8.112836268800161!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91ad3d7e7e61ab93%3A0xc3b8a1c97a5180f1!2sTrujillo%2C%20Peru!5e0!3m2!1sen!2sus!4v1683100000000!5m2!1sen!2sus\" width=\"100%\" height=\"350\" style=\"border:0; border-radius: 8px;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </article>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <aside>\r\n");
      out.write("                <h5>Sobre nosotros</h5>\r\n");
      out.write("                <a href=\"https://www.linkedin.com/in/ismael-cornejo-14186b296/\" target=\"_blank\" class=\"social-link\">\r\n");
      out.write("                    <img src=\"imagenes/linkedin.svg\" alt=\"LinkedIn\">\r\n");
      out.write("                    Perfil en LinkedIn\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"https://github.com/Itshaize\" target=\"_blank\" class=\"social-link\">\r\n");
      out.write("                    <img src=\"imagenes/github.svg\" alt=\"Github\">\r\n");
      out.write("                    Perfil en GitHub\r\n");
      out.write("                </a>\r\n");
      out.write("            </aside>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-socials\">\r\n");
      out.write("            <a href=\"https://facebook.com/reivan\" target=\"_blank\"><img src=\"imagenes/facebook.svg\" alt=\"Facebook\"></a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/leonard.studios/\" target=\"_blank\"><img src=\"imagenes/instagram.svg\" alt=\"Instagram\"></a>\r\n");
      out.write("            <a href=\"https://www.tiktok.com/@itshaiz_\" target=\"_blank\"><img src=\"imagenes/tiktok.svg\" alt=\"TikTok\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>&copy; 2026 Ismael Cornejo</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
