/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2026-05-04 03:48:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Registro - REIVAN</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link href=\"CSS/estilos.css?v=3\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header-principal\">\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("            <a href=\"index.jsp\"><img src=\"imagenes/logo_r_transparent.png\" alt=\"Logo Reivan\" class=\"logo-imagen\" style=\"border: none;\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"textos-header\">\r\n");
      out.write("            <h1>REIVAN</h1>\r\n");
      out.write("            <h2 class=\"destacado\">Premium Computer Store</h2>\r\n");
      out.write("            <h4 id=\"favorito\">Mejora tu Pc Hoy mismo</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"index.jsp\">Inicio</a>\r\n");
      out.write("        <a href=\"construccion.jsp\">Servicios</a>\r\n");
      out.write("        <a href=\"construccion.jsp\">Contacto</a>\r\n");
      out.write("        <a href=\"login.jsp\">Iniciar Sesión</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <main style=\"max-width: 800px; margin: 40px auto; background-color: var(--white); border-radius: 8px;\">\r\n");
      out.write("        <div class=\"row no-gutters\" style=\"box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); border: 1px solid #ddd; border-radius: 8px; overflow: hidden; padding: 30px; background-color: white;\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <h3 class=\"mb-4\" style=\"color: var(--primary-color); font-weight: bold; border-bottom: 2px solid var(--primary-color); display: inline-block; padding-bottom: 5px;\">Crear una Cuenta</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <form action=\"respuesta.jsp\" method=\"post\" id=\"formRegistro\">\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"form-group col-md-6 text-left\">\r\n");
      out.write("                            <label for=\"txtNombre\" style=\"font-weight: bold; color: var(--text-main);\">Nombre Completo</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"txtNombre\" name=\"txtNombre\" placeholder=\"Ingresa tu nombre completo\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-6 text-left\">\r\n");
      out.write("                            <label for=\"txtCedula\" style=\"font-weight: bold; color: var(--text-main);\">Cédula</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"txtCedula\" name=\"txtCedula\" placeholder=\"Ej: 1712345678\" required maxlength=\"10\" pattern=\"\\d{10}\" title=\"Debe contener 10 dígitos\">\r\n");
      out.write("                            <small class=\"form-text text-muted\">Debe tener exactamente 10 números.</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"form-group col-md-6 text-left\">\r\n");
      out.write("                            <label for=\"mFecha\" style=\"font-weight: bold; color: var(--text-main);\">Mes y Año de Nacimiento</label>\r\n");
      out.write("                            <input type=\"month\" class=\"form-control\" id=\"mFecha\" name=\"mFecha\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-6 text-left\">\r\n");
      out.write("                            <label for=\"cmbEstado\" style=\"font-weight: bold; color: var(--text-main);\">Estado Civil</label>\r\n");
      out.write("                            <select id=\"cmbEstado\" name=\"cmbEstado\" class=\"form-control\" required>\r\n");
      out.write("                                <option value=\"\" disabled selected>Seleccione su estado...</option>\r\n");
      out.write("                                <option value=\"Soltero/a\">Soltero/a</option>\r\n");
      out.write("                                <option value=\"Casado/a\">Casado/a</option>\r\n");
      out.write("                                <option value=\"Divorciado/a\">Divorciado/a</option>\r\n");
      out.write("                                <option value=\"Viudo/a\">Viudo/a</option>\r\n");
      out.write("                                <option value=\"Unión Libre\">Unión Libre</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group text-left\">\r\n");
      out.write("                        <label style=\"font-weight: bold; color: var(--text-main); display: block;\">Lugar de Residencia</label>\r\n");
      out.write("                        <div class=\"form-check form-check-inline\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"radio\" name=\"rdResidencia\" id=\"residenciaNorte\" value=\"Norte\" required>\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"residenciaNorte\">Norte</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check form-check-inline\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"radio\" name=\"rdResidencia\" id=\"residenciaSur\" value=\"Sur\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"residenciaSur\">Sur</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check form-check-inline\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"radio\" name=\"rdResidencia\" id=\"residenciaCentro\" value=\"Centro\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"residenciaCentro\">Centro</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check form-check-inline\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"radio\" name=\"rdResidencia\" id=\"residenciaValles\" value=\"Valles\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"residenciaValles\">Valles</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-row\">\r\n");
      out.write("                        <div class=\"form-group col-md-6 text-left\">\r\n");
      out.write("                            <label for=\"cColor\" style=\"font-weight: bold; color: var(--text-main);\">Color Favorito</label>\r\n");
      out.write("                            <input type=\"color\" class=\"form-control\" id=\"cColor\" name=\"cColor\" value=\"#0056b3\" style=\"height: 44px;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-6 text-left\">\r\n");
      out.write("                            <label style=\"font-weight: bold; color: var(--text-main); display: block;\">¿Incluir Foto de Perfil?</label>\r\n");
      out.write("                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"optFoto\" id=\"optFotoSi\" value=\"si\" checked>\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"optFotoSi\">Sí</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"optFoto\" id=\"optFotoNo\" value=\"no\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"optFotoNo\">No</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"wrapperFoto\" style=\"margin-top: 10px;\">\r\n");
      out.write("                                <input type=\"file\" class=\"form-control-file\" id=\"fileFoto\" name=\"fileFoto\" accept=\"image/*\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mt-4\">\r\n");
      out.write("                        <button type=\"submit\" id=\"btnSubmit\" class=\"btn text-white w-100 mb-2\" style=\"background-color: var(--primary-color); font-weight: bold; border: none; padding: 12px; font-size: 1.1em;\">\r\n");
      out.write("                            <span id=\"btnText\">Completar Registro</span>\r\n");
      out.write("                            <span id=\"btnLoader\" style=\"display: none;\">Procesando...</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"reset\" class=\"btn btn-outline-secondary w-100\" style=\"padding: 10px;\">Limpiar Formulario</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-socials\">\r\n");
      out.write("            <a href=\"https://facebook.com/reivan\" target=\"_blank\"><img src=\"imagenes/facebook.svg\" alt=\"Facebook\"></a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/leonard.studios/\" target=\"_blank\"><img src=\"imagenes/instagram.svg\" alt=\"Instagram\"></a>\r\n");
      out.write("            <a href=\"https://www.tiktok.com/@itshaiz_\" target=\"_blank\"><img src=\"imagenes/tiktok.svg\" alt=\"TikTok\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>&copy; 2026 Ismael Cornejo</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            // Toggle para la foto\r\n");
      out.write("            $('input[name=\"optFoto\"]').change(function() {\r\n");
      out.write("                if ($(this).val() === 'no') {\r\n");
      out.write("                    $('#wrapperFoto').fadeOut(200);\r\n");
      out.write("                    $('#fileFoto').val(''); // Limpiar el archivo seleccionado\r\n");
      out.write("                } else {\r\n");
      out.write("                    $('#wrapperFoto').fadeIn(200);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Efecto de carga al enviar\r\n");
      out.write("            $('#formRegistro').on('submit', function() {\r\n");
      out.write("                $('#btnText').hide();\r\n");
      out.write("                $('#btnLoader').show();\r\n");
      out.write("                $('#btnSubmit').css('pointer-events', 'none');\r\n");
      out.write("                $('#btnSubmit').css('opacity', '0.7');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
