/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2026-05-04 03:47:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;
import java.time.Period;
import java.time.YearMonth;

public final class respuesta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.time.Period");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.YearMonth");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String nombre     = request.getParameter("txtNombre") != null ? request.getParameter("txtNombre") : "";
    String cedula     = request.getParameter("txtCedula") != null ? request.getParameter("txtCedula") : "";
    String fechaStr   = request.getParameter("mFecha");
    String color      = request.getParameter("cColor") != null ? request.getParameter("cColor") : "transparent";
    String foto       = request.getParameter("fileFoto");
    String estado     = request.getParameter("cmbEstado") != null ? request.getParameter("cmbEstado") : "No especificado";
    String residencia = request.getParameter("rdResidencia") != null ? request.getParameter("rdResidencia") : "No especificada";

    String edadTexto = "No calculada";
    if (fechaStr != null && !fechaStr.isEmpty()) {
        try {
            // Aseguramos que tome al menos el formato YYYY-MM
            String fechaParsing = fechaStr.length() > 7 ? fechaStr.substring(0, 7) : fechaStr;
            YearMonth nacimiento = YearMonth.parse(fechaParsing);
            YearMonth hoy = YearMonth.now();
            int edad = Period.between(nacimiento.atDay(1), hoy.atDay(1)).getYears();
            edadTexto = edad + " años";
        } catch (Exception e) {
            edadTexto = "Formato inválido (" + fechaStr + ")";
        }
    }

    String provinciaHtml = "<span class='text-muted'>No determinada</span>";
    if (cedula != null && cedula.length() >= 2) {
        try {
            String codigoStr = cedula.substring(0, 2);
            int codigo = Integer.parseInt(codigoStr);
            String nombreProv = "";
            switch (codigo) {
                case 1:  nombreProv = "Azuay"; break;
                case 2:  nombreProv = "Bolívar"; break;
                case 3:  nombreProv = "Cañar"; break;
                case 4:  nombreProv = "Carchi"; break;
                case 5:  nombreProv = "Cotopaxi"; break;
                case 6:  nombreProv = "Chimborazo"; break;
                case 7:  nombreProv = "El Oro"; break;
                case 8:  nombreProv = "Esmeraldas"; break;
                case 9:  nombreProv = "Guayas"; break;
                case 10: nombreProv = "Imbabura"; break;
                case 11: nombreProv = "Loja"; break;
                case 12: nombreProv = "Los Ríos"; break;
                case 13: nombreProv = "Manabí"; break;
                case 14: nombreProv = "Morona Santiago"; break;
                case 15: nombreProv = "Napo"; break;
                case 16: nombreProv = "Pastaza"; break;
                case 17: nombreProv = "Pichincha"; break;
                case 18: nombreProv = "Tungurahua"; break;
                case 19: nombreProv = "Zamora Chinchipe"; break;
                case 20: nombreProv = "Galápagos"; break;
                case 21: nombreProv = "Sucumbíos"; break;
                case 22: nombreProv = "Orellana"; break;
                case 23: nombreProv = "Santo Domingo de los Tsáchilas"; break;
                case 24: nombreProv = "Santa Elena"; break;
                default: nombreProv = ""; break;
            }
            
            if (!nombreProv.isEmpty()) {
                provinciaHtml = "<div class='provincia-badge'><span class='prov-codigo'>" + codigoStr + "</span> <span class='prov-nombre'>" + nombreProv + "</span></div>";
            } else {
                provinciaHtml = "<span class='text-danger'>Código no válido (" + codigoStr + ")</span>";
            }
        } catch (NumberFormatException e) {
            provinciaHtml = "<span class='text-danger'>Cédula inválida</span>";
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Registro Exitoso - REIVAN</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link href=\"CSS/estilos.css?v=3\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        .provincia-badge {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            font-family: 'Courier New', Courier, monospace;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .prov-codigo {\r\n");
      out.write("            color: #008cba; /* Azul similar a la imagen */\r\n");
      out.write("            font-size: 1.1em;\r\n");
      out.write("        }\r\n");
      out.write("        .prov-nombre {\r\n");
      out.write("            color: #8e44ad; /* Morado similar a la imagen */\r\n");
      out.write("            font-size: 1.1em;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header-principal\">\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("            <a href=\"index.jsp\"><img src=\"imagenes/logo_r_transparent.png\" alt=\"Logo Reivan\" class=\"logo-imagen\" style=\"border: none;\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"textos-header\">\r\n");
      out.write("            <h1>REIVAN</h1>\r\n");
      out.write("            <h2 class=\"destacado\">Premium Computer Store</h2>\r\n");
      out.write("            <h4 id=\"favorito\">Mejora tu Pc Hoy mismo</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"index.jsp\">Inicio</a>\r\n");
      out.write("        <a href=\"construccion.jsp\">Servicios</a>\r\n");
      out.write("        <a href=\"construccion.jsp\">Contacto</a>\r\n");
      out.write("        <a href=\"login.jsp\">Iniciar Sesión</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <main style=\"max-width: 600px; margin: 40px auto; padding: 0 15px;\">\r\n");
      out.write("        <div class=\"respuesta-card\">\r\n");
      out.write("            <div class=\"respuesta-header\">\r\n");
      out.write("                <div class=\"respuesta-icono\">&#10003;</div>\r\n");
      out.write("                <h3>¡Registro Exitoso!</h3>\r\n");
      out.write("                <p>Bienvenido, <strong>");
      out.print( nombre );
      out.write("</strong></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"respuesta-body\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"registro-seccion\">\r\n");
      out.write("                    <span class=\"registro-seccion-titulo\">Información Personal</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Cédula</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\">");
      out.print( cedula );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Provincia de Origen</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\">");
      out.print( provinciaHtml );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Edad</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\">");
      out.print( edadTexto );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Mes/Año de Nacimiento</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\">");
      out.print( fechaStr );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Estado Civil</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\">");
      out.print( estado );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Residencia</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\">");
      out.print( residencia );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"registro-seccion\" style=\"margin-top: 20px;\">\r\n");
      out.write("                    <span class=\"registro-seccion-titulo\">Adicional</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Foto de Perfil</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\" style=\"color: var(--primary-color);\">\r\n");
      out.write("                        ");

                            String optFoto = request.getParameter("optFoto");
                            if ("no".equals(optFoto)) {
                                out.print("No solicitada");
                            } else {
                                out.print((foto != null && !foto.isEmpty()) ? foto : "No cargada");
                            }
                        
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"respuesta-fila\">\r\n");
      out.write("                    <span class=\"respuesta-label\">Color Favorito</span>\r\n");
      out.write("                    <span class=\"respuesta-valor\">\r\n");
      out.write("                        <span style=\"display:inline-block; width:40px; height:22px; background-color:");
      out.print( color );
      out.write("; border:1px solid #ccc; border-radius:4px; vertical-align:middle;\"></span>\r\n");
      out.write("                        <span style=\"margin-left: 8px;\">");
      out.print( color );
      out.write("</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"text-center mt-4\">\r\n");
      out.write("                    <a href=\"registro.jsp\" class=\"btn-registro-secondary\" style=\"text-decoration:none; padding: 10px 30px;\">Volver al Formulario</a>\r\n");
      out.write("                    <a href=\"login.jsp\" class=\"btn-registro-primary\" style=\"text-decoration:none; padding: 10px 30px; margin-left: 10px;\">Iniciar Sesión</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-socials\">\r\n");
      out.write("            <a href=\"https://facebook.com/reivan\" target=\"_blank\"><img src=\"imagenes/facebook.svg\" alt=\"Facebook\"></a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/leonard.studios/\" target=\"_blank\"><img src=\"imagenes/instagram.svg\" alt=\"Instagram\"></a>\r\n");
      out.write("            <a href=\"https://www.tiktok.com/@itshaiz_\" target=\"_blank\"><img src=\"imagenes/tiktok.svg\" alt=\"TikTok\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>&copy; 2026 Ismael Cornejo</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
